kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: loyalty
          image: localhost:5000/payment
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 5
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: payment
spec:
  type: LoadBalancer
  ports:
    - port: 8092
      targetPort: 8092
      protocol: TCP
  #      nodePort: 31000
  selector:
    app: payment
