kind: Deployment
apiVersion: apps/v1
metadata:
  name: loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty
  template:
    metadata:
      labels:
        app: loyalty
    spec:
      containers:
        - name: loyalty
          image: localhost:5000/loyalty
          imagePullPolicy: Always
          ports:
            - containerPort: 8093
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8093
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8093
            initialDelaySeconds: 5
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: loyalty
spec:
  type: LoadBalancer
  ports:
    - port: 8093
      targetPort: 8093
      protocol: TCP
  #      nodePort: 31000
  selector:
    app: loyalty
