kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
        - name: order-processor
          image: localhost:5000/order-processor
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 5
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: order-processor
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  #      nodePort: 31000
  selector:
    app: order-processor
