server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:myDB-order-processor
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    initialize: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true